---
# Default Kibana configuration from kibana-docker.

server.name: kibana
server.host: "0"
elasticsearch.url: http://elasticsearch:9200
xpack.monitoring.ui.container.elasticsearch.enabled: true
console.enabled: false
xpack.apm.enabled: false
xpack.ml.enabled: false
xpack.graph.enabled: false
xpack.grokdebugger.enabled: false
xpack.security.enabled: false